# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: whoami
#   namespace: traefik
# spec:
#   parentRefs:
#   - name: traefik-gateway  # This Gateway is automatically created by Traefik 
#   hostnames:
#   - "whoami.docker.localhost"
#   rules:
#   - matches:
#     - path:
#         type: PathPrefix
#         value: /
#     backendRefs:
#     - name: whoami
#       port: 80